module.exports = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  ERROR_RECEIVED: 'ERROR_RECEIVED',

  USER_RECEIVED: 'USER_RECEIVED',
  USER_UPDATED: 'USER_UPDATED',
  USER_FETCHED: 'USER_FETCHED',

  SONGS_RECEIVED: 'SONGS_RECEIVED',
  SONGS_ERROR: 'SONGS_ERROR'
}
