module.exports = {
  LOGIN_USER: 'LOGIN_USER',
  LOGOUT_USER: 'LOGOUT_USER',
  ERROR_RECEIVED: 'ERROR_RECEIVED',

  USER_RECEIVED: 'USER_RECEIVED',
  USER_UPDATED: 'USER_UPDATED',
  USER_FETCHED: 'USER_FETCHED',

  SONGS_RECEIVED: 'SONGS_RECEIVED',
  SONGS_ERROR: 'SONGS_ERROR',
  SONG_RECEIVED: 'SONG_RECEIVED',
  NEXT_SONG: 'NEXT_SONG',
  ARTIST_SONGS: 'ARTIST_SONGS',
  QUEUE_REMOVE: 'QUEUE_REMOVE',

  LIKED_SONGS: 'LIKED_SONGS',
  LIKE_MADE: 'LIKE_MADE',
  UNLIKED: 'UNLIKED',

  ADD_SONG: 'ADD_SONG'
}
